-- 1. 뉴스 피드 테이블
CREATE TABLE feeds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    category TEXT NOT NULL,
    url TEXT NOT NULL,
    UNIQUE(category, url)
);

-- 2. 뉴스 아카이브 테이블
CREATE TABLE archives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    date DATE NOT NULL,
    category TEXT NOT NULL,
    content TEXT,
    UNIQUE(date, category)
);

-- 3. 통계 테이블
CREATE TABLE daily_stats (
    date DATE PRIMARY KEY,
    views INT DEFAULT 0
);

CREATE TABLE global_stats (
    key TEXT PRIMARY KEY,
    value INT DEFAULT 0
);

-- 초기값 (옵션)
INSERT INTO global_stats (key, value) VALUES ('total_views', 0) ON CONFLICT DO NOTHING;
